package com.sciencepixel.consumer

import com.sciencepixel.config.KafkaConfig
import com.sciencepixel.domain.VideoHistory
import com.sciencepixel.domain.VideoStatus
import com.sciencepixel.event.KafkaEventPublisher
import com.sciencepixel.event.RssNewItemEvent
import com.sciencepixel.event.ScriptCreatedEvent
import com.sciencepixel.repository.VideoHistoryRepository
import com.sciencepixel.service.GeminiService
import com.sciencepixel.service.LogPublisher
import com.fasterxml.jackson.databind.ObjectMapper
import org.springframework.kafka.annotation.KafkaListener
import org.springframework.stereotype.Component
import java.time.LocalDateTime
import java.util.*

@Component
class ScriptConsumer(
    private val geminiService: GeminiService,
    private val videoHistoryRepository: VideoHistoryRepository,
    private val eventPublisher: KafkaEventPublisher,
    private val logPublisher: LogPublisher,
    private val objectMapper: ObjectMapper
) {

    @KafkaListener(
        topics = [KafkaConfig.TOPIC_RSS_NEW_ITEM],
        groupId = KafkaConfig.GROUP_MAIN
    )
    fun consumeRssItem(message: String) {
        try {
            val event = objectMapper.readValue(message, RssNewItemEvent::class.java)
            logPublisher.info("shorts-controller", "Process Started: ${event.title}", "URL: ${event.url}")
            println("▶️ [ScriptConsumer] Received RSS item: ${event.title}")

            // 1. Create or Get History (Idempotency)
            val history = getOrCreateHistory(event)
            
            // 전역 차단 상태 확인 (업로드 차단 상태이면 아예 생성을 안 하는 것이 토큰 절약에 유리할 수 있음)
            // 여기서는 일단 기존 로직대로 진행하되, 중복 호출 체크만 강화함
            
            // 이미 완료되었거나 업로드된 경우 건너뜀
            if (history.status == VideoStatus.COMPLETED || history.status == VideoStatus.UPLOADED) {
                println("⚠️ Video already completed/uploaded for: ${event.title}. Skipping Gemini call.")
                return
            }

            // 이미 파이프라인 진행 중인 경우 건너뜀
            // (새로운 체계에서는 CREATING 상태가 모든 진행 중인 상태를 포함합니다)
            // 단, 최초 생성인 경우에도 CREATING이므로, 여기서 getOrCreateHistory 이후의 상태를 세밀하게 볼 필요가 없으면 그대로 둡니다.
            // 여기서는 중복 발행 방지를 위해 체크합니다.
            // 5분 이내 중복 체크 로직 제거 (VideoProcessor가 이미 CREATING으로 생성해서 넘기므로 여기서 막힘)
            // if (history.status == VideoStatus.CREATING && history.updatedAt.isAfter(LocalDateTime.now().minusMinutes(5))) {
            //      println("⏭️ Video already in pipeline (Status: ${history.status}) for: ${event.title}. Skipping Gemini call to save tokens.")
            //      return
            // }

            // 2. Call Gemini
            println("🤖 generating script for: ${event.title}...")
            val scriptResponse = geminiService.writeScript(event.title, event.title) // RSS summary might be null, use title or fetch content if needed

            if (scriptResponse.scenes.isEmpty()) {
                println("⚠️ Empty script generated. Marking as FAILED.")
                videoHistoryRepository.save(history.copy(
                    status = VideoStatus.FAILED,
                    failureStep = "SCRIPT",
                    errorMessage = "Empty script generated by Gemini",
                    updatedAt = LocalDateTime.now()
                ))
                return
            }

            // 3. Update History with Script Data (Stay in CREATING)
            val updatedHistory = videoHistoryRepository.save(history.copy(
                status = VideoStatus.CREATING,
                title = scriptResponse.title,
                description = scriptResponse.description,
                tags = scriptResponse.tags,
                sources = scriptResponse.sources,
                updatedAt = LocalDateTime.now()
            ))

            // 4. Publish next event
            eventPublisher.publishScriptCreated(ScriptCreatedEvent(
                videoId = updatedHistory.id!!,
                title = scriptResponse.title,
                script = objectMapper.writeValueAsString(scriptResponse.scenes), // Serialize scenes to string to pass along
                summary = scriptResponse.description,
                sourceLink = event.url,
                keywords = scriptResponse.tags
            ))

            logPublisher.info("shorts-controller", "Script Generated: ${scriptResponse.title}", "Scenes: ${scriptResponse.scenes.size}ea", traceId = updatedHistory.id)
            println("✅ [ScriptConsumer] Script created & event published: ${event.title}")

        } catch (e: Exception) {
            logPublisher.error("shorts-controller", "Script Generation Failed", "Error: ${e.message}")
            println("❌ [ScriptConsumer] Error: ${e.message}")
            e.printStackTrace()
            // Mark as FAILED in DB
            val event = objectMapper.readValue(message, RssNewItemEvent::class.java)
            videoHistoryRepository.findByLink(event.url)?.let { 
                videoHistoryRepository.save(it.copy(
                    status = VideoStatus.FAILED, 
                    failureStep = "SCRIPT",
                    errorMessage = e.message ?: "Unknown Script Generation Error",
                    updatedAt = LocalDateTime.now()
                ))
            }
        }
    }

    private fun getOrCreateHistory(event: RssNewItemEvent): VideoHistory {
        // Simple check by link (assuming unique per news)
        val existing = videoHistoryRepository.findByLink(event.url)
        if (existing != null) return existing

        val initialVideo = VideoHistory(
            id = UUID.randomUUID().toString(),
            title = event.title,
            summary = "", // Initial summary
            link = event.url,
            status = VideoStatus.CREATING,
            createdAt = LocalDateTime.now(),
            updatedAt = LocalDateTime.now()
        )
        return try {
            videoHistoryRepository.save(initialVideo)
        } catch (e: org.springframework.dao.DuplicateKeyException) {
            println("⚠️ Race condition detected for link: ${event.url}. Returning existing record.")
            videoHistoryRepository.findByLink(event.url) ?: throw IllegalStateException("Record should exist but not found: ${event.url}")
        } catch (e: Exception) {
             // Fallback for other potential race conditions or DB errors
             val checkAgain = videoHistoryRepository.findByLink(event.url)
             if (checkAgain != null) return checkAgain
             throw e
        }
    }
}
