package com.sciencepixel.consumer

import com.sciencepixel.config.KafkaConfig
import com.sciencepixel.domain.VideoHistory
import com.sciencepixel.domain.VideoStatus
import com.sciencepixel.event.KafkaEventPublisher
import com.sciencepixel.event.RssNewItemEvent
import com.sciencepixel.event.ScriptCreatedEvent
import com.sciencepixel.repository.VideoHistoryRepository
import com.sciencepixel.service.GeminiService
import com.sciencepixel.service.LogPublisher
import com.fasterxml.jackson.databind.ObjectMapper
import org.springframework.kafka.annotation.KafkaListener
import org.springframework.stereotype.Component
import java.time.LocalDateTime
import java.util.*

@Component
@org.springframework.boot.autoconfigure.condition.ConditionalOnProperty(
    name = ["app.feature.consumer-script"],
    havingValue = "true",
    matchIfMissing = true
)
class ScriptConsumer(
    private val geminiService: GeminiService,
    private val videoHistoryRepository: VideoHistoryRepository,
    private val eventPublisher: KafkaEventPublisher,
    private val logPublisher: LogPublisher,
    private val objectMapper: ObjectMapper,
    @org.springframework.beans.factory.annotation.Value("\${SHORTS_CHANNEL_ID:science}") private val channelId: String
) {

    @KafkaListener(
        topics = [KafkaConfig.TOPIC_RSS_NEW_ITEM],
        groupId = "\${spring.kafka.consumer.group-id:\${SHORTS_CHANNEL_ID:science}-group}"
    )
    fun consumeRssItem(message: String) {
        try {
            val event = objectMapper.readValue(message, RssNewItemEvent::class.java)
            
            // Channel Filter
            // If this instance is the dedicated 'renderer', it processes ALL channels.
            if (channelId != "renderer" && event.channelId != channelId) {
                return
            }

            // 1. Create or Get History (Idempotency)
            val history = getOrCreateHistory(event)
            
            // 전역 차단 상태 확인 (업로드 차단 상태이면 아예 생성을 안 하는 것이 토큰 절약에 유리할 수 있음)
            // 여기서는 일단 기존 로직대로 진행하되, 중복 호출 체크만 강화함
            
            // 이미 완료되었거나 업로드된 경우 건너뜀
            if (history.status == VideoStatus.COMPLETED || history.status == VideoStatus.UPLOADED) {
                println("⚠️ Video already completed/uploaded for: ${event.title}. Skipping Gemini call.")
                return
            }

            // 이미 파이프라인 진행 중인 경우 건너뜀
            // 1.5 Safety Check & Claim (Locking)
            // Valid states: QUEUED (New), SCRIPTING (Retry started by Scheduler), RETRY_QUEUED (Just in case)
            if (history.status != VideoStatus.QUEUED && history.status != VideoStatus.SCRIPTING) {
                 if (history.status == VideoStatus.FAILED || history.status == VideoStatus.RETRY_QUEUED) {
                     println("⚠️ [ScriptConsumer] Invalid state for processing: ${history.status}. Reverting to RETRY_QUEUED.")
                     videoHistoryRepository.save(history.copy(
                         status = VideoStatus.RETRY_QUEUED,
                         updatedAt = LocalDateTime.now()
                     ))
                     return
                 }
                 println("⏭️ Skipping: Video is in terminal or advanced state (${history.status}) for: ${event.title}")
                 return
            }
            
            // Claim the job (Set to SCRIPTING)
            val processingHistory = videoHistoryRepository.save(history.copy(
                status = VideoStatus.SCRIPTING,
                updatedAt = LocalDateTime.now()
            ))
            println("🔒 Claimed job (QUEUED/RETRY -> SCRIPTING): ${event.title}")

            // 2. Call Gemini
            println("🤖 generating script for: ${event.title}...")
            val content = event.summary ?: event.title
            val scriptResponse = geminiService.writeScript(event.title, content)

            if (scriptResponse.scenes.isEmpty()) {
                println("⚠️ Empty script generated. Marking as FAILED.")
                videoHistoryRepository.save(history.copy(
                    status = VideoStatus.FAILED,
                    failureStep = "SCRIPT",
                    errorMessage = "Empty script generated by Gemini",
                    updatedAt = LocalDateTime.now()
                ))
                return
            }

            // 3. Update History with Script Data (Stay in SCRIPTING)
            val updatedHistory = videoHistoryRepository.save(history.copy(
                status = VideoStatus.SCRIPTING,
                title = scriptResponse.title,
                description = scriptResponse.description,
                tags = scriptResponse.tags,
                sources = scriptResponse.sources,
                updatedAt = LocalDateTime.now()
            ))

            // 4. Publish next event
            eventPublisher.publishScriptCreated(ScriptCreatedEvent(
                channelId = channelId, // 추가
                videoId = updatedHistory.id!!,
                title = scriptResponse.title,
                script = objectMapper.writeValueAsString(scriptResponse.scenes),
                summary = scriptResponse.description,
                sourceLink = event.url,
                keywords = scriptResponse.tags
            ))

            logPublisher.info("shorts-controller", "Script Generated: ${scriptResponse.title}", "Scenes: ${scriptResponse.scenes.size}ea", traceId = updatedHistory.id)
            println("✅ [$channelId] Script created & event published: ${event.title}")

        } catch (e: Exception) {
            logPublisher.error("shorts-controller", "Script Generation Failed", "Error: ${e.message}")
            println("❌ [$channelId] Error: ${e.message}")
            e.printStackTrace()
            // Mark as FAILED in DB
            val event = objectMapper.readValue(message, RssNewItemEvent::class.java)
            videoHistoryRepository.findByChannelIdAndLink(channelId, event.url)?.let { 
                videoHistoryRepository.save(it.copy(
                    status = VideoStatus.FAILED, 
                    failureStep = "SCRIPT",
                    errorMessage = e.message ?: "Unknown Script Generation Error",
                    updatedAt = LocalDateTime.now()
                ))
            }
        }
    }

    private fun getOrCreateHistory(event: RssNewItemEvent): VideoHistory {
        // Simple check by link (assuming unique per news per channel)
        val existing = videoHistoryRepository.findByChannelIdAndLink(channelId, event.url)
        if (existing != null) return existing

        val initialVideo = VideoHistory(
            id = UUID.randomUUID().toString(),
            channelId = channelId, // 추가
            title = event.title,
            summary = "", 
            link = event.url,
            status = VideoStatus.QUEUED,
            createdAt = LocalDateTime.now(),
            updatedAt = LocalDateTime.now()
        )
        return try {
            videoHistoryRepository.save(initialVideo)
        } catch (e: org.springframework.dao.DuplicateKeyException) {
            println("⚠️ Race condition detected for link: ${event.url} in channel $channelId. Returning existing record.")
            videoHistoryRepository.findByChannelIdAndLink(channelId, event.url) ?: throw IllegalStateException("Record should exist but not found: ${event.url}")
        } catch (e: Exception) {
             val checkAgain = videoHistoryRepository.findByChannelIdAndLink(channelId, event.url)
             if (checkAgain != null) return checkAgain
             throw e
        }
    }
}
